spring:
  application:
    name: turbine
    
server:
  port: 5001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
turbine:
  app-config: zuul, web, display, admin
  cluster-name-expression: new String("default")

---
#生产环境
spring:
  profiles: pro
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.13:2001/eureka

  