spring:
  application:
    name: zuul
    
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
    web: /**
    display: /display/**
    admin: /admin/**
    sso: /sso/**
      #解决Cookies问题
  sensitive-headers:
       #解决重定向问题
  add-host-header: true
      #设置Hystrix隔离策略为线程池
  ribbon-isolation-strategy: thread
      #每个路由使用独立的线程池
  thread-pool.use-separate-thread-pools: true
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
            
#开启actuator监控                      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
#生产环境
spring:
  profiles: pro
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.13:2001/eureka
        